### ISSUE TITLE
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by dfmateus** [guilhermewolf/aws-loadbalancer-ansible#3]
After added and run, the error appear to me.

ansible-playbook playbook.yml

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/user/aws-loadbalancer-ansible/playbook.yml': line 29, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - cloud_init_data_facts:
      ^ here

**Here is the line inside playbook.yml': line 29**
- name: Wait for cloud init to finish
  hosts: cluster
  gather_facts: False
  become: yes
  tasks:
    - cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 50
      delay: 5

Any ideas ?

**Comment by guilhermewolf** [comment]
Can you tell me which version of ansible you are using?

The module cloud_init_data_fact is only available in 2.6 version.

**Comment by dfmateus** [comment]
I've updated ansible to 2.8 version and fix the error.

Thanks.
